# Generated by Django 6.0.6 on 2026-09-22 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Horario de inicio')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Horario de termino')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('palestrantes', models.TextField(blank=True, verbose_name='Palestrantes')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('regras', models.TextField(blank=True, verbose_name='Regras e restricoes')),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carga horaria')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='eventos/imagens/')),
                ('limite_inscricoes', models.PositiveIntegerField(verbose_name='Quantidade maxima de inscritos')),
                ('inscricoes_encerram_em', models.DateTimeField(verbose_name='Limite de inscricao')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('ENCERRADO', 'Inscricoes encerradas'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_evento', 'hora_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('consentiu_lgpd', models.BooleanField(default=False)),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento')),
            ],
            options={
                'ordering': ['-inscrito_em'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='eventos/certificados/')),
                ('gerado_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro_envio', models.TextField(blank=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='eventos.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField(default=False)),
                ('confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presenca', to='eventos.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='CampoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chave', models.SlugField(max_length=100)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_adicionais', to='eventos.evento')),
            ],
            options={
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'chave'), name='evento_campo_chave_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelado_em__isnull', True)), fields=('evento', 'cpf'), name='inscricao_ativa_evento_cpf_unica'),
        ),
    ]
