# Generated by Django 6.0.6 on 2026-09-30 13:03

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=eventos.models.caminho_certificado_evento),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to=eventos.models.caminho_imagem_evento),
        ),
    ]
