# Generated by Django 6.0.6 on 2026-09-30 13:18

import core.configured_storage
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_certificado_arquivo_alter_evento_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=core.configured_storage.ConfiguredRootStorage('EVENTOS_DIR'), upload_to=eventos.models.caminho_certificado_evento),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.FileField(blank=True, null=True, storage=core.configured_storage.ConfiguredRootStorage('EVENTOS_DIR'), upload_to=eventos.models.caminho_imagem_evento),
        ),
    ]
