# Generated by Django 6.0.6 on 2026-06-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('UPLOAD', 'Upload de Arquivo'), ('CRIAR_PASTA', 'Criação de Subpasta'), ('RENOMEAR', 'Renomear Item'), ('APAGAR', 'Mover para Lixeira')], max_length=20, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição do Evento')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('caminho_item', models.TextField(blank=True, null=True, verbose_name='Caminho do Arquivo/Pasta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
