# Generated by Django 6.0.6 on 2026-06-26 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='caminho_item',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
