# Generated by Django 6.0.6 on 2026-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logauditoria_acao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLixeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=255)),
                ('caminho_original', models.CharField(max_length=1024)),
                ('caminho_na_lixeira', models.CharField(max_length=1024)),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
