# Generated by Django 6.0.6 on 2026-06-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registrolixeira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrolixeira',
            options={'verbose_name': 'Registro de Lixeira'},
        ),
        migrations.RenameField(
            model_name='registrolixeira',
            old_name='nome_item',
            new_name='nome_na_lixeira',
        ),
        migrations.RemoveField(
            model_name='registrolixeira',
            name='caminho_na_lixeira',
        ),
    ]
