# Generated by Django 6.0.6 on 2026-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='caminho_item',
            field=models.TextField(blank=True, null=True),
        ),
    ]
