# Generated by Django 6.0.6 on 2026-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_logauditoria_caminho_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='password_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da alteração de senha'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='Senha foi alterada no primeiro acesso'),
        ),
    ]
