# Generated by Django 6.0.6 on 2026-07-01 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Registro')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Início da Jornada)'), ('ALMOCO_SAIDA', 'Saída para Almoço'), ('ALMOCO_RETORNO', 'Retorno do Almoço'), ('SAIDA', 'Saída (Fim da Jornada)'), ('EXTR_ENTRADA', 'Início de Hora Extra'), ('EXTR_SAIDA', 'Fim de Hora Extra')], max_length=20, verbose_name='Tipo de Registro')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data_hora'],
            },
        ),
    ]
