# Generated by Django 6.0.6 on 2026-07-01 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_perfilfuncionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('ATESTADO', 'Atestado Médico'), ('LICENCA', 'Licença'), ('FALTA_JUST', 'Falta Justificada')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
