# Generated by Django 6.0.6 on 2026-07-01 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Registro'),
        ),
    ]
