# Generated by Django 6.0.6 on 2026-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_alter_registroponto_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='atestados/%Y/%m/%d/'),
        ),
    ]
