# Generated by Django 6.0.6 on 2026-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_ocorrencia_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilfuncionario',
            name='horario_entrada',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='perfilfuncionario',
            name='horario_saida',
            field=models.TimeField(default='17:00'),
        ),
    ]
