# Generated by Django 6.0.6 on 2026-07-08 12:40

import django.db.models.deletion
import ponto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0006_perfilfuncionario_horario_entrada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Início da Jornada)'), ('ALMOCO_SAIDA', 'Saída para Almoço'), ('ALMOCO_RETORNO', 'Retorno do Almoço'), ('SAIDA', 'Saída (Fim da Jornada)')], max_length=20, verbose_name='Tipo de Registro'),
        ),
        migrations.CreateModel(
            name='Contracheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=ponto.models.path_contracheque)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
