# Generated by Django 6.0.6 on 2026-08-04 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.TextField(verbose_name='Despacho / Instruções')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Recebimento'), ('RECEBIDO', 'Recebido / Em Análise'), ('CONCLUIDO', 'Concluído / Arquivado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='core.documento', verbose_name='Documento')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
                ('setor_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_setor', to='core.setor', verbose_name='Setor de Destino')),
                ('setor_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_setor', to='core.setor', verbose_name='Setor de Origem')),
                ('usuario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário Específico (Opcional)')),
            ],
            options={
                'verbose_name': 'Tramitação de Documento',
                'verbose_name_plural': 'Tramitações de Documentos',
                'ordering': ['-data_envio'],
            },
        ),
    ]
