# Generated by Django 6.0.6 on 2026-08-04 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='aguardar_resposta',
            field=models.BooleanField(default=False, verbose_name='Aguardar Resposta'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título da Tramitação'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário Específico (Opcional)'),
        ),
        migrations.CreateModel(
            name='AnexoTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tramitacoes/anexos/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tramitacao.tramitacao', verbose_name='Tramitação')),
            ],
        ),
    ]
