# Generated by Django 6.0.6 on 2026-08-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0002_tramitacao_aguardar_resposta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacao',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='documento',
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='prontuario',
            field=models.CharField(default='000/2026', max_length=100, verbose_name='Prontuário / Número do Documento'),
            preserve_default=False,
        ),
    ]
