# Generated by Django 6.0.6 on 2026-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0003_remove_tramitacao_data_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Tramitação', 'verbose_name_plural': 'Tramitações'},
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='prontuario',
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='tipo_documento',
            field=models.CharField(choices=[('MEMORANDO', 'Memorando'), ('OFICIO', 'Ofício'), ('REQUERIMENTO', 'Requerimento'), ('PORTARIA', 'Portaria'), ('PARECER', 'Parecer Técnico'), ('OUTRO', 'Outro (Especificar)')], default='MEMORANDO', max_length=30, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Assunto / Título'),
        ),
        migrations.DeleteModel(
            name='AnexoTramitacao',
        ),
    ]
