# Generated by Django 6.0.6 on 2026-08-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0004_alter_tramitacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='tipo_documento',
            field=models.CharField(choices=[('MEMORANDO', 'Memorando'), ('OFICIO', 'Ofício'), ('REQUERIMENTO', 'Requerimento'), ('PORTARIA', 'Portaria'), ('PARECER', 'Parecer Técnico'), ('OUTRO', 'Outro')], default='MEMORANDO', max_length=30, verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='AnexoTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tramitacoes_anexos/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tramitacao.tramitacao', verbose_name='Tramitação')),
            ],
            options={
                'verbose_name': 'Anexo de Tramitação',
                'verbose_name_plural': 'Anexos de Tramitação',
            },
        ),
    ]
