# Generated by Django 6.0.6 on 2026-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0005_alter_tramitacao_tipo_documento_anexotramitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número do Protocolo'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Recebimento'), ('RECEBIDO', 'Recebido / Em Análise'), ('DEVOLVIDO', 'Devolvido'), ('CONCLUIDO', 'Concluído / Arquivado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
