# Generated by Django 6.0.6 on 2026-08-10 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil'),
        ('tramitacao', '0006_alter_tramitacao_protocolo_alter_tramitacao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('setor_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor')),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='tramitacao.tramitacao')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tramitacoes/historico/')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tramitacao.historicotramitacao')),
            ],
        ),
    ]
