# Generated by Django 6.0.6 on 2026-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0007_historicotramitacao_anexohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='auto_devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='data_limite_resposta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
