# Generated by Django 6.0.6 on 2026-08-13 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil'),
        ('tramitacao', '0008_tramitacao_auto_devolvido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexotramitacao',
            options={},
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documento', verbose_name='Documento GED'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='setor_criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_setor_criador', to='core.setor'),
        ),
        migrations.AlterField(
            model_name='anexohistorico',
            name='arquivo',
            field=models.FileField(upload_to='tramitacoes/historico_anexos/'),
        ),
        migrations.AlterField(
            model_name='anexotramitacao',
            name='arquivo',
            field=models.FileField(upload_to='tramitacoes/anexos/'),
        ),
        migrations.AlterField(
            model_name='anexotramitacao',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anexotramitacao',
            name='tramitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tramitacao.tramitacao'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='aguardar_resposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='despacho',
            field=models.TextField(verbose_name='Despacho'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='protocolo',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Número do Protocolo'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='setor_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_destino', to='core.setor'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_origem', to='core.setor'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('CONCLUIDO', 'Concluído'), ('DEVOLVIDO', 'Devolvido'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='tipo_documento',
            field=models.CharField(max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='titulo',
            field=models.CharField(default='', max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_destino', to=settings.AUTH_USER_MODEL),
        ),
    ]
