# Generated by Django 6.0.6 on 2026-08-13 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0009_alter_anexotramitacao_options_tramitacao_criador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tramitacao',
            options={},
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='auto_devolvido',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='data_recebimento',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='tramitacao',
            name='setor_criador',
        ),
        migrations.AddField(
            model_name='anexotramitacao',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='despacho',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('DEVOLVIDO', 'Devolvido'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='tipo_documento',
            field=models.CharField(choices=[('OFICIO', 'Ofício'), ('MEMORANDO', 'Memorando'), ('CIRCULAR', 'Circular'), ('REQUERIMENTO', 'Requerimento'), ('PROCESSO', 'Processo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_destinadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicotramitacao',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramitacao.setor'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='setor_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes_recebidas', to='tramitacao.setor'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes_enviadas', to='tramitacao.setor'),
        ),
    ]
