# Generated by Django 6.0.6 on 2026-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0011_alter_tramitacao_setor_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='tipo_documento',
            field=models.CharField(choices=[('OFICIO', 'Ofício'), ('MEMORANDO', 'Memorando'), ('CIRCULAR', 'Circular'), ('REQUERIMENTO', 'Requerimento'), ('PROCESSO', 'Processo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=100, verbose_name='Tipo de Documento'),
        ),
    ]
