# Generated by Django 6.0.6 on 2026-08-14 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0012_alter_tramitacao_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexotramitacao',
            name='historico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tramitacao.historicotramitacao'),
        ),
        migrations.AlterField(
            model_name='anexohistorico',
            name='historico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramitacao.historicotramitacao'),
        ),
    ]
