# Generated by Django 6.0.6 on 2026-08-18 14:20

import tramitacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0013_anexotramitacao_historico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexohistorico',
            name='arquivo',
            field=models.FileField(upload_to=tramitacao.models.caminho_upload_tramitacao),
        ),
        migrations.AlterField(
            model_name='anexotramitacao',
            name='arquivo',
            field=models.FileField(upload_to=tramitacao.models.caminho_upload_tramitacao),
        ),
    ]
