# Generated by Django 6.0.6 on 2026-08-21 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0014_alter_anexohistorico_arquivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='aguardando_resposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='assinado',
            field=models.BooleanField(default=False, verbose_name='Assinado'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='assinado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_assinados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='exige_assinatura',
            field=models.BooleanField(default=False, verbose_name='Exigir assinatura do destinatário'),
        ),
    ]
