# Generated by Django 6.0.6 on 2026-08-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0015_tramitacao_aguardando_resposta_tramitacao_assinado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='assinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='assinado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_assinadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='exige_assinatura',
            field=models.BooleanField(default=False),
        ),
    ]
