# Generated by Django 6.0.6 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0016_alter_tramitacao_assinado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='protocolo',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número do Protocolo'),
        ),
    ]
