# Generated by Django 6.0.6 on 2026-08-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0017_alter_tramitacao_protocolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacao',
            name='aguardando_resposta',
        ),
    ]
