# Generated by Django 6.0.6 on 2026-08-25 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfil_password_change_date_perfil_password_changed'),
        ('tramitacao', '0018_remove_tramitacao_aguardando_resposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='remetente_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_enviadas_original', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='setor_origem_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_setor_origem_original', to='core.setor'),
        ),
    ]
