# Generated by Django 6.0.6 on 2026-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0019_tramitacao_remetente_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicotramitacao',
            name='aguardar_resposta',
            field=models.BooleanField(default=False),
        ),
    ]
