# Generated by Django 6.0.6 on 2026-09-09 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacao', '0020_historicotramitacao_aguardar_resposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinado', models.BooleanField(default=False)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='tramitacao.tramitacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_tramitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_assinatura', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tramitacao', 'usuario'), name='assinatura_unica_por_usuario')],
            },
        ),
    ]
