import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Define a pasta raiz do projeto (onde está o manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega o arquivo .env explicitamente pelo caminho absoluto
dotenv_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path)

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Pega a chave do ambiente
SECRET_KEY = os.getenv('SECRET_KEY')

# Verificação de segurança (isso vai te avisar no log se a chave estiver vazia)
if not SECRET_KEY:
    raise ImproperlyConfigured("ERRO: A variável SECRET_KEY não foi carregada. Verifique o arquivo .env em " + str(dotenv_path))

# Caminhos dos arquivos do GED. Os valores abaixo preservam o ambiente local
# atual, mas permitem configuração diferente no servidor.
GED_BASE_DIR = os.getenv('GED_BASE_DIR', r'C:\TESTE\GED')
SETORES_BASE_DIR = os.getenv('SETORES_BASE_DIR', r'C:\TESTE\SETORES')
LIXEIRA_DIR = os.getenv('LIXEIRA_DIR', r'C:\TESTE\GED_LIXEIRA')
TRAMITACAO_DIR = os.getenv('TRAMITACAO_DIR', r'C:\TESTE\TRAMITACAO')
EVENTOS_DIR = os.getenv('EVENTOS_DIR', r'D:\EVENTOS')
ECARTA_DIR = os.getenv('ECARTA_DIR', r'D:\ECARTA')
PONTO_DIR = os.getenv('PONTO_DIR', r'D:\PONTO')
os.makedirs(PONTO_DIR, exist_ok=True)
GED_PF_GROUPS = env_list('GED_PF_GROUPS', 'GED_PESSOA_FISICA')
GED_PJ_GROUPS = env_list('GED_PJ_GROUPS', 'GED_PESSOA_JURIDICA')
PONTO_RH_GROUPS = env_list(
    'PONTO_RH_GROUPS',
    'DEPARTAMENTO PESSOAL,DP,ADMINISTRATIVO,ADM',
)
UPLOAD_MAX_SIZE = int(os.getenv('UPLOAD_MAX_SIZE', str(20 * 1024 * 1024)))
UPLOAD_ALLOWED_EXTENSIONS = env_list(
    'UPLOAD_ALLOWED_EXTENSIONS',
    '.pdf,.doc,.docx,.xls,.xlsx,.csv,.png,.jpg,.jpeg,.gif,.txt',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = TRAMITACAO_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep debug disabled outside local development.
DEBUG = env_bool('DEBUG', default=False)
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', default=False)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@crfpb.org.br')

SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=SECURE_SSL_REDIRECT)
    CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=SECURE_SSL_REDIRECT)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # GED:
    'core',
    'tramitacao',
    'ecarta',
    'ponto',
    'eventos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.EnforcePasswordChangeMiddleware',  # Força alteração de senha no primeiro acesso
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.usuario_setor',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

LOGIN_URL = 'inicio'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'ponto_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(PONTO_DIR, 'ponto.log'),
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'core': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'tramitacao': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'ecarta': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'ponto': {'handlers': ['console', 'ponto_file'], 'level': 'INFO', 'propagate': False},
    },
}