# Generated by Django 6.0.6 on 2026-09-30 13:03

import django.db.models.deletion
import ecarta.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEcarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=30, unique=True)),
                ('arquivo_servico', models.FileField(upload_to=ecarta.models.caminho_arquivo_lote)),
                ('arquivo_resposta', models.FileField(upload_to=ecarta.models.caminho_arquivo_lote)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_ecarta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote e-Carta',
                'verbose_name_plural': 'Lotes e-Carta',
                'ordering': ['-criado_em'],
            },
        ),
    ]
