# Generated by Django 6.0.6 on 2026-09-30 13:18

import core.configured_storage
import ecarta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarta', '0002_loteecarta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteecarta',
            name='arquivo_resposta',
            field=models.FileField(storage=core.configured_storage.ConfiguredRootStorage('ECARTA_DIR'), upload_to=ecarta.models.caminho_arquivo_lote),
        ),
        migrations.AlterField(
            model_name='loteecarta',
            name='arquivo_servico',
            field=models.FileField(storage=core.configured_storage.ConfiguredRootStorage('ECARTA_DIR'), upload_to=ecarta.models.caminho_arquivo_lote),
        ),
    ]
